apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    service: backend-user
